### ISSUE TITLE
Make the swap button say Swap! unless if you want to swap anywhere on the screen

### ISSUE THREAD

**Issue by ghost** [EbaadImran/swap#16]
You should make the swap button say "Swap!" if you aren't making it where you can click anywhere to swap (which you shuld because everyone i know is complaining and wanting it to be that way because the button is always to small and in the corner so you have to hold it with two hands and it is just not good and friendly).

The reason is because the game is called "Swap!" not "Swap". Just for symbolism.

But you can still do this until you make it be anywhere on the screen.

**Comment by EbaadImran** [comment]
Fixed it
